# Generated by Django 5.2.13 on 2026-08-27 20:51

import accounting.models
import core.file_validation
import core.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factures', '0009_invoice_is_credit_note_invoice_issued_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activité comptable',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_review', to='factures.invoice')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Fournisseur')),
                ('supplier_key', models.CharField(editable=False, max_length=200)),
                ('reference', models.CharField(max_length=100, verbose_name='Numéro de facture')),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date de facture')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('paid_on', models.DateField(blank=True, null=True, verbose_name='Payée le')),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant TTC (€)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TVA indiquée (€)')),
                ('category', models.CharField(choices=[('supplies', 'Produits et fournitures'), ('equipment', 'Matériel'), ('subcontracting', 'Sous-traitance'), ('transport', 'Transport et déplacements'), ('premises', 'Locaux et charges'), ('services', 'Services et abonnements'), ('other', 'Autres')], default='other', max_length=30, verbose_name='Catégorie')),
                ('notes', models.TextField(blank=True, max_length=4000, verbose_name='Note pour le cabinet')),
                ('file', models.FileField(storage=core.storage.PrivateStorage(), upload_to=accounting.models.supplier_upload_path, validators=[core.file_validation.validate_document], verbose_name='Pièce justificative')),
                ('file_sha256', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, max_length=2000)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_supplier_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'facture fournisseur',
                'ordering': ['-issue_date', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('supplier_key', 'reference'), name='unique_supplier_reference'), models.CheckConstraint(condition=models.Q(('total_ttc__gt', 0)), name='supplier_positive_total'), models.CheckConstraint(condition=models.Q(('vat_amount__gte', 0), ('vat_amount__lte', models.F('total_ttc'))), name='supplier_valid_vat')],
            },
        ),
    ]
