# Generated by Django 5.2.13 on 2026-08-28 12:18

import accounting.models
import core.file_validation
import core.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom du document')),
                ('kind', models.CharField(choices=[('bank', 'Relevé bancaire'), ('tax', 'Document fiscal'), ('social', 'Document social'), ('contract', 'Contrat'), ('insurance', 'Assurance / attestation'), ('other', 'Autre document')], default='other', max_length=20, verbose_name='Type de document')),
                ('document_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date de classement')),
                ('notes', models.TextField(blank=True, max_length=4000, verbose_name='Note pour le cabinet')),
                ('file', models.FileField(storage=core.storage.PrivateStorage(), upload_to=accounting.models.document_upload_path, validators=[core.file_validation.validate_document], verbose_name='Document')),
                ('file_sha256', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name': 'document comptable',
                'ordering': ['-document_date', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='supplierinvoice',
            name='unique_supplier_reference',
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='issue_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Date de facture'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro de facture'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='total_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant TTC (€)'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TVA indiquée (€)'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('supplier_key', ''), _negated=True), models.Q(('reference', ''), _negated=True)), fields=('supplier_key', 'reference'), name='unique_known_supplier_reference'),
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_accounting_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
