# Generated by Django 3.2.25 on 2025-12-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0007_quote_email_body_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='email_body_html',
            field=models.TextField(blank=True, default='', help_text="Message HTML inséré dans l'email d'envoi du devis (optionnel)."),
        ),
    ]
