# Generated by Django 5.2 on 2026-06-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_base_price_service_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_alt',
            field=models.CharField(blank=True, help_text="Description courte de l'image pour l'accessibilité et le référencement (attribut alt). À défaut, le titre du service est utilisé.", max_length=255, verbose_name='Texte alternatif (alt)'),
        ),
    ]
