# Generated by Django 5.2.5 on 2025-10-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_commune_message_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
    ]
