# Generated by Django 5.2.5 on 2025-10-30 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, help_text="Description courte utilisée sur la page d'accueil.", max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Prix de base en euros pour ce service.', max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Durée estimée en minutes pour exécuter ce service.')),
                ('image', models.ImageField(blank=True, help_text='Image illustrative du service.', null=True, upload_to='services')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(help_text="Identifiant d'URL généré automatiquement.", max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text='Catégorie du service', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='services.service')),
            ],
            options={
                'verbose_name': 'tâche',
                'verbose_name_plural': 'tâches',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='services_se_slug_4657d0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='services_se_is_acti_91b7ea_idx'),
        ),
    ]
