# Generated by Django 5.2.5 on 2025-10-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icône de la catégorie (image téléversée)', null=True, upload_to='categories'),
        ),
    ]
