# Generated by Django 5.2.5 on 2025-10-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='commune',
            field=models.CharField(default='Matoury', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='zip_code',
            field=models.PositiveIntegerField(default=97351, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.CharField(choices=[('bricolage', 'Bricolage'), ('peinture', 'Peinture'), ('renovation', 'Rénovation'), ('service_vert', 'Service Espace Vert'), ('partenariat', 'Partenariat'), ('autre', 'Autre')], max_length=50),
        ),
    ]
