# Generated by Django 5.2.8 on 2025-12-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_message_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='street',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
