# Generated by Django 5.2.9 on 2025-12-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_message_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='city',
            field=models.CharField(blank=True, help_text='Ville (optionnel)', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='street',
            field=models.CharField(blank=True, help_text='Rue (optionnel)', max_length=200),
        ),
    ]
