# Generated by Django 5.2.5 on 2025-10-30 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('team', models.CharField(blank=True, help_text="Nom de l'équipe en charge de cette tâche (information interne)", max_length=100)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'À venir'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('overdue', 'En retard')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tâche',
                'verbose_name_plural': 'tâches',
                'ordering': ['due_date', 'title'],
            },
        ),
    ]
