# Generated by Django 5.2.12 on 2026-04-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0008_alter_quote_options_client_deleted_at_and_more'),
        ('factures', '0007_invoice_command_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='factures_in_status_3489af_idx'),
        ),
    ]
