# Generated by Django 5.2.13 on 2026-08-27 20:51

import core.storage
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def mark_existing_issued(apps, schema_editor):
    Invoice = apps.get_model("factures", "Invoice")
    Invoice.objects.exclude(status__in=["draft", "demo"]).update(issued_at=models.F("created_at"))
    Invoice.objects.filter(status="avoir").update(is_credit_note=True)


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0008_invoice_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_credit_note',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(mark_existing_issued, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=core.storage.PrivateStorage(), upload_to='factures'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
