# Generated by Django 5.2.17 on 2026-09-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0010_alter_quote_pdf_alter_quotephoto_image_and_more'),
        ('factures', '0009_invoice_is_credit_note_invoice_issued_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client facturé. Repris du devis lorsque la facture en découle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='devis.client'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client'], name='factures_in_client__e506a8_idx'),
        ),
    ]
