# Generated by Django 5.2.5 on 2025-10-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text='Adresse(s) e‑mail des destinataires, séparées par des virgules.', max_length=500)),
                ('cc', models.CharField(blank=True, help_text='Adresses e‑mail en copie carbone, séparées par des virgules.', max_length=500)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, help_text='Fichier à joindre au message, facultatif.', null=True, upload_to='messages/attachments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('failed', 'Échec')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'message envoyé',
                'verbose_name_plural': 'messages envoyés',
                'ordering': ['-created_at'],
            },
        ),
    ]
