# Generated by Django 5.2.9 on 2026-01-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messagethread_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(help_text='Contenu HTML généré par les templates prédéfinis.'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(help_text='Message content'),
        ),
    ]
