# Generated by Django 5.2.13 on 2026-08-27 20:51

import core.file_validation
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_emailmessage_body_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Fichier à joindre au message, facultatif.', null=True, storage=core.storage.PrivateStorage(), upload_to='messages/attachments', validators=[core.file_validation.validate_document]),
        ),
    ]
