# Generated by Django 5.2.8 on 2025-12-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='base_price',
        ),
        migrations.AddField(
            model_name='service',
            name='unit_type',
            field=models.CharField(default='forfait', help_text="Type d'unité pour la saisie (ex. m², heure, forfait).", max_length=50, verbose_name='Unité de mesure'),
        ),
    ]
