# Generated by Django 5.1.4 on 2024-12-23 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0002_alter_service_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='service',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='client_detail', to='luxama.service'),
        ),
    ]
