# Generated by Django 5.1.4 on 2024-12-23 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0003_alter_client_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tache',
        ),
        migrations.RemoveField(
            model_name='client',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='client',
        ),
        migrations.AlterField(
            model_name='devis',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='luxama.client'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='service',
            field=models.ManyToManyField(related_name='devis', to='luxama.service'),
        ),
    ]
