# Generated by Django 5.1.4 on 2024-12-23 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0004_delete_tache_remove_client_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='categorie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='service', to='luxama.categorie'),
        ),
    ]
