# Generated by Django 5.1.4 on 2024-12-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0005_service_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
