# Generated by Django 5.1.4 on 2025-01-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0006_client_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='localisation',
        ),
        migrations.AddField(
            model_name='client',
            name='code_postal',
            field=models.CharField(default='97300', max_length=5),
        ),
    ]
