# Generated by Django 5.1.4 on 2025-01-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0008_categorie_slug_client_ville_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
