# Generated by Django 5.1.4 on 2025-01-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0009_alter_categorie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(default='slug', max_length=100, unique=True),
        ),
    ]
