# Generated by Django 5.1.4 on 2025-01-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0010_alter_categorie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='slug',
        ),
    ]
