# Generated by Django 5.1.4 on 2025-01-01 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0011_remove_categorie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', message='Le numéro de téléphone doit contenir entre 10 et 15 chiffres.')]),
        ),
        migrations.AlterField(
            model_name='devis',
            name='prix_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
