# Generated by Django 5.1.4 on 2025-01-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0012_categorie_slug_alter_client_telephone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={},
        ),
    ]
