# Generated by Django 5.1.4 on 2025-01-01 22:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0013_alter_categorie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom'], 'verbose_name': 'Categorie', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='devis',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='categorie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='service', to='luxama.categorie'),
        ),
    ]
