# Generated by Django 5.1.4 on 2025-01-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0014_alter_categorie_options_remove_categorie_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
