# Generated by Django 5.1.4 on 2025-01-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0015_categorie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
