# Generated by Django 5.1.4 on 2025-01-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0016_alter_categorie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='categorie',
        ),
        migrations.AddField(
            model_name='service',
            name='servive',
            field=models.CharField(choices=[('Nettoyage', 'Nettoyage'), ('Peinture', 'Peinture'), ('Rénovation', 'Rénovation'), ('Bricolage', 'Bricolage'), ('Espace Vert', 'Espace Vert'), ('Autre', 'Autre')], default='Autre', max_length=100),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
