# Generated by Django 5.1.4 on 2025-01-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0017_remove_service_categorie_service_servive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='servive',
            field=models.CharField(choices=[('Nettoyage', 'Nettoyage'), ('Peinture', 'Peinture'), ('Renovation', 'Rénovation'), ('Bricolage', 'Bricolage'), ('Espace Vert', 'Espace Vert'), ('Autre', 'Autre')], default='Autre', max_length=100),
        ),
    ]
