# Generated by Django 5.1.4 on 2025-01-01 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0019_categorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
