# Generated by Django 5.1.4 on 2025-01-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0020_delete_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='servive',
            new_name='service',
        ),
    ]
