# Generated by Django 5.1.4 on 2025-01-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0022_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='localisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
