# Generated by Django 5.1.4 on 2025-01-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0023_tache_localisation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devis',
        ),
    ]
