# Generated by Django 5.1.4 on 2025-01-05 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0025_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
