# Generated by Django 5.1.4 on 2025-01-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0026_alter_tache_date_debut_alter_tache_date_fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devis',
            old_name='prix_total',
            new_name='prix_initial',
        ),
        migrations.AddField(
            model_name='devis',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En attente', max_length=20),
        ),
    ]
