# Generated by Django 5.1.4 on 2025-02-01 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0027_rename_prix_total_devis_prix_initial_devis_reduction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tache',
            options={},
        ),
    ]
