# Generated by Django 5.1.4 on 2025-02-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0028_alter_client_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='date_de_validite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.TextField(blank=True, default="Il n'y a aucune description pour cette tâche.", null=True),
        ),
    ]
