# Generated by Django 5.1.4 on 2025-02-04 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0029_devis_date_de_validite_devis_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date_de_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_de_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
