# Generated by Django 5.1.4 on 2025-02-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0030_alter_devis_date_de_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='numero_devis',
            field=models.CharField(default=2, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
