# Generated by Django 5.1.4 on 2025-02-11 20:52

import django.core.validators
import luxama.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxama', '0031_devis_numero_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date_de_validite',
            field=models.DateField(default=luxama.models.date_de_validite_default),
        ),
        migrations.AlterField(
            model_name='devis',
            name='prix_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
