# Generated by Django 5.2.9 on 2025-12-21 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devis', '0006_quote_public_token'),
        ('factures', '0007_invoice_command_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_granted_at', models.DateTimeField(auto_now_add=True, help_text='When access was granted to this document')),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='When the client last accessed this document', null=True)),
                ('client_user', models.ForeignKey(help_text='Client user who has access to this document', on_delete=django.db.models.deletion.CASCADE, related_name='accessible_documents', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, help_text='Invoice document accessible to the client', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_accesses', to='factures.invoice')),
                ('quote', models.ForeignKey(blank=True, help_text='Quote document accessible to the client', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_accesses', to='devis.quote')),
            ],
            options={
                'verbose_name': 'Client Document Access',
                'verbose_name_plural': 'Client Document Accesses',
                'indexes': [models.Index(fields=['client_user', 'access_granted_at'], name='core_client_client__a03214_idx'), models.Index(fields=['quote', 'client_user'], name='core_client_quote_i_37a882_idx'), models.Index(fields=['invoice', 'client_user'], name='core_client_invoice_1f5c6f_idx')],
                'unique_together': {('client_user', 'invoice'), ('client_user', 'quote')},
            },
        ),
    ]
