# Generated by Django 5.2.9 on 2025-12-21 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UINotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short notification title', max_length=200)),
                ('message', models.TextField(help_text='Detailed notification message')),
                ('notification_type', models.CharField(choices=[('task_completed', 'Task Completed'), ('task_assigned', 'Task Assigned'), ('quote_validated', 'Quote Validated'), ('invoice_created', 'Invoice Created'), ('message_received', 'Message Received'), ('account_created', 'Account Created'), ('document_updated', 'Document Updated'), ('general', 'General')], default='general', help_text='Type of notification for categorization and styling', max_length=50)),
                ('read', models.BooleanField(default=False, help_text='Whether the user has read this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was marked as read', null=True)),
                ('link_url', models.CharField(blank=True, help_text='Optional URL to link to related content', max_length=500)),
                ('user', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='ui_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UI Notification',
                'verbose_name_plural': 'UI Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='core_uinoti_user_id_6d149f_idx'), models.Index(fields=['user', 'notification_type'], name='core_uinoti_user_id_79d744_idx')],
            },
        ),
    ]
