# Generated by Django 5.2.9 on 2025-12-21 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_uinotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_type', models.CharField(choices=[('client', 'Client Portal'), ('worker', 'Worker Portal'), ('admin', 'Admin Portal')], help_text='Type of portal accessed', max_length=20)),
                ('login_time', models.DateTimeField(auto_now_add=True, help_text='When the user logged into the portal')),
                ('logout_time', models.DateTimeField(blank=True, help_text='When the user logged out or session ended', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text="IP address of the user's session")),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the browser')),
                ('pages_visited', models.PositiveIntegerField(default=0, help_text='Number of pages visited during this session')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp for this session')),
                ('session_duration', models.DurationField(blank=True, help_text='Total duration of the session (calculated on logout)', null=True)),
                ('user', models.ForeignKey(help_text='User who accessed the portal', on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portal Session',
                'verbose_name_plural': 'Portal Sessions',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='core_portal_user_id_917ea2_idx'), models.Index(fields=['portal_type', '-login_time'], name='core_portal_portal__1b4906_idx'), models.Index(fields=['ip_address', '-login_time'], name='core_portal_ip_addr_b59449_idx'), models.Index(fields=['-login_time'], name='core_portal_login_t_9a477c_idx')],
            },
        ),
    ]
