# Generated by Django 5.2.12 on 2026-04-09 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_portal_session'),
        ('devis', '0008_alter_quote_options_client_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPortalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre affiché dans le portail client', max_length=180)),
                ('description', models.TextField(blank=True, help_text='Résumé ou consignes associées au document')),
                ('category', models.CharField(choices=[('general', 'Document général'), ('contract', 'Contrat'), ('report', 'Rapport'), ('certificate', 'Attestation'), ('photo', 'Photo / visuel'), ('other', 'Autre')], default='general', max_length=30)),
                ('file', models.FileField(upload_to='client_portal_documents/%Y/%m')),
                ('is_pinned', models.BooleanField(default=False, help_text='Met en avant le document dans le portail')),
                ('is_published', models.BooleanField(default=True, help_text='Masque ou affiche le document côté client')),
                ('expires_at', models.DateField(blank=True, help_text="Date limite d'accès optionnelle", null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(help_text='Client destinataire du document', on_delete=django.db.models.deletion.CASCADE, related_name='portal_documents', to='devis.client')),
                ('published_by', models.ForeignKey(blank=True, help_text='Collaborateur ayant publié le document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_client_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document portail client',
                'verbose_name_plural': 'Documents portail client',
                'ordering': ['-is_pinned', '-published_at'],
                'indexes': [models.Index(fields=['client', 'is_published', '-published_at'], name='core_client_client__d0e8a6_idx'), models.Index(fields=['expires_at'], name='core_client_expires_933891_idx')],
            },
        ),
    ]
