# Generated by Django 5.2.12 on 2026-04-30 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clientportaldocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='uinotification',
            name='notification_type',
            field=models.CharField(choices=[('task_completed', 'Task Completed'), ('task_updated', 'Task Updated'), ('task_assigned', 'Task Assigned'), ('quote_validated', 'Quote Validated'), ('invoice_created', 'Invoice Created'), ('message_received', 'Message Received'), ('account_created', 'Account Created'), ('document_updated', 'Document Updated'), ('general', 'General')], default='general', help_text='Type of notification for categorization and styling', max_length=50),
        ),
        migrations.CreateModel(
            name='ClientSubmittedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre ou objet du document', max_length=200)),
                ('category', models.CharField(choices=[('justificatif', 'Pièce justificative'), ('photo', 'Photo (avant/après travaux)'), ('contrat_signe', 'Contrat signé'), ('autre', 'Autre document')], default='autre', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Commentaire ou précision du client')),
                ('file', models.FileField(upload_to='client_submissions/%Y/%m')),
                ('status', models.CharField(choices=[('pending', 'En attente de traitement'), ('reviewed', 'Traité'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text="Notes internes de l'admin")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('client_user', models.ForeignKey(help_text='Client ayant soumis le document', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_documents', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_client_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document soumis par client',
                'verbose_name_plural': 'Documents soumis par clients',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
