# Generated by Django 5.2.12 on 2026-04-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_client_submitted_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre affiche sous la photo', max_length=200)),
                ('category', models.CharField(choices=[('nettoyage', 'Nettoyage'), ('espaces_verts', 'Espaces verts'), ('renovation', 'Renovation'), ('autre', 'Autre')], default='nettoyage', max_length=30)),
                ('image', models.ImageField(upload_to='realisations/%Y')),
                ('description', models.TextField(blank=True, help_text='Description courte (optionnel)')),
                ('is_published', models.BooleanField(default=True, help_text='Afficher dans la galerie')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Realisation',
                'verbose_name_plural': 'Realisations',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
