# Generated by Django 5.2.13 on 2026-08-27 20:51

import core.file_validation
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_realisation_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=16, unique=True)),
                ('value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='clientportaldocument',
            name='file',
            field=models.FileField(storage=core.storage.PrivateStorage(), upload_to='client_portal_documents/%Y/%m', validators=[core.file_validation.validate_document]),
        ),
        migrations.AlterField(
            model_name='clientsubmitteddocument',
            name='file',
            field=models.FileField(storage=core.storage.PrivateStorage(), upload_to='client_submissions/%Y/%m', validators=[core.file_validation.validate_document]),
        ),
    ]
