# Generated by Django 3.2.25 on 2025-12-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('upcoming', 'À venir'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('overdue', 'En retard'), ('almost_overdue', 'Presque en retard')], default='upcoming', max_length=20),
        ),
    ]
