# Generated by Django 5.2.9 on 2025-12-31 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_assigned_to_task_completed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Workers assigned to this task', limit_choices_to={'groups__name': 'Workers'}, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
