# Generated by Django 5.1.6 on 2025-02-18 20:46

import django.core.validators
import django.db.models.deletion
import luxama.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=150)),
                ('code_postal', models.CharField(default='97300', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('service', models.CharField(choices=[('Nettoyage', 'Nettoyage'), ('Peinture', 'Peinture'), ('Renovation', 'Rénovation'), ('Bricolage', 'Bricolage'), ('Espace Vert', 'Espace Vert'), ('Autre', 'Autre')], default='Autre', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default="Il n'y a aucune description pour cette tâche.", null=True)),
                ('localisation', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En attente', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_initial', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_de_creation', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_de_validite', models.DateField(default=luxama.models.date_de_validite_default)),
                ('numero_devis', models.CharField(editable=False, max_length=50, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='luxama.client')),
                ('service', models.ManyToManyField(related_name='devis', to='luxama.service')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_de_creation'],
            },
        ),
    ]
