# Generated by Django 5.2.12 on 2026-04-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0007_alter_quoteitem_tax_rate'),
        ('services', '0003_remove_service_base_price_service_unit_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': 'devis', 'verbose_name_plural': 'devis'},
        ),
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='devis_clien_email_728ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['full_name'], name='devis_clien_full_na_60ef0e_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='devis_quote_status_74c455_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['number'], name='devis_quote_number_b1717a_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['issue_date'], name='devis_quote_issue_d_cf6ce7_idx'),
        ),
    ]
