# Generated by Django 5.2.13 on 2026-06-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0008_alter_quote_options_client_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='deadline',
            field=models.CharField(blank=True, choices=[('standard', 'Standard (sous 1 semaine)'), ('express', 'Express (48 h)'), ('immediat', 'Immédiat (24 h)')], max_length=20, verbose_name='Délai souhaité'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='service_type',
            field=models.CharField(blank=True, choices=[('nettoyage', 'Nettoyage'), ('espaces_verts', 'Espaces verts'), ('renovation', 'Rénovation')], max_length=20, verbose_name='Type de service'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='surface',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Surface (m²)'),
        ),
    ]
