# Generated by Django 5.2.13 on 2026-08-27 20:51

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0009_quoterequest_deadline_quoterequest_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=core.storage.PrivateStorage(), upload_to='devis'),
        ),
        migrations.AlterField(
            model_name='quotephoto',
            name='image',
            field=models.ImageField(storage=core.storage.PrivateStorage(), upload_to='devis/photos'),
        ),
        migrations.AlterField(
            model_name='quoterequestphoto',
            name='image',
            field=models.ImageField(storage=core.storage.PrivateStorage(), upload_to='devis/requests/photos', verbose_name='Fichier'),
        ),
    ]
