# Generated by Django 5.2.9 on 2025-12-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_portal_access',
            field=models.DateTimeField(blank=True, help_text='Last time user accessed their portal', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences for email and UI notifications'),
        ),
    ]
