# Generated by Django 5.2.9 on 2025-12-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_last_portal_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('worker', 'Ouvrier'), ('admin_business', 'Administrateur Business'), ('admin_technical', 'Administrateur Technique')], default='client', max_length=20),
        ),
    ]
