# Generated by Django 5.2.9 on 2026-01-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_new_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text="Si True, l'utilisateur doit changer son mot de passe à la prochaine connexion"),
        ),
    ]
