# Generated by Django 5.2.13 on 2026-08-27 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_accounts_pr_role_fae1f3_idx'),
        ('devis', '0010_alter_quote_pdf_alter_quotephoto_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accounting_firm',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cabinet comptable'),
        ),
        migrations.AddField(
            model_name='profile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_profiles', to='devis.client'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('accountant', 'Comptable'), ('client', 'Client'), ('worker', 'Ouvrier'), ('admin_business', 'Administrateur Business'), ('admin_technical', 'Administrateur Technique')], default='client', max_length=20),
        ),
    ]
