# Generated by Django 5.2.5 on 2025-10-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('prospection', 'Prospection'), ('sav', 'Service après‑vente'), ('partenariat', 'Partenariat'), ('gros_volumes', 'Gros volumes'), ('autre', 'Autre')], max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic', 'created_at'], name='contact_mes_topic_6d7e0e_idx')],
            },
        ),
    ]
