# Generated by Django 5.2.5 on 2025-10-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_message_commune_message_zip_code_alter_message_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='commune',
            new_name='city',
        ),
    ]
